### ISSUE TITLE
Lack of Documentation

### ISSUE THREAD

**Issue by GazbonicAcid** [DaedalusGame/Modular-Diversity#1]
Please make documentation for it, otherwise it's totally useless.
There's no point in downloading it if we can't use it.
[CurseForge](https://minecraft.curseforge.com/projects/modular-diversity?comment=4)

**Comment by DaedalusGame** [comment]
https://github.com/DaedalusGame/Modular-Diversity/wiki
Probably done, unless there's something left unclear by that.
