### ISSUE TITLE
GT-CE Energy Hatch

### ISSUE THREAD

**Issue by pyure** [DaedalusGame/Modular-Diversity#11]
Probably more work than its worth, but I'd absolutely **love** to see a hatch that would communicate with the GT-CE energy system (finally arrived in Alpha this week).

GT-CE (for those unaware) is the 1.12 Gregtech successor.

**Comment by TedKnudsen** [comment]
@DaedalusGame if it helps, it uses capabilities.  At least one other compat was written the other day (turbodiesel, of nuclearcraft fame)

**Comment by pyure** [comment]
GT-CE is now in Beta and has done a bit of a cleanup on the energy net.  There's a bunch of people who'd love to make multiblocks that are GT compatible ;)

**Comment by HellFirePvP** [comment]
Done via main ModularMachinery with 1.9.6 and newer.
Doesn't need to be done in ModularDiversity.

This issue might aswell be closed now.

**Comment by pyure** [comment]
Thanks kindly HellFirePvP.

@DaedalusGame I hope you don't mind my presumption at closing.   Thanks for considering it sir.
