### ISSUE TITLE
Crash On World Load Using Embers Input Hatches

### ISSUE THREAD

**Issue by Boolyman** [DaedalusGame/Modular-Diversity#12]
I keep getting this crash 
https://pastebin.com/UZgszgad

I am simply trying to make a recipe that requires a little bit of Embers, and a few pieces of Ember's Ash, to generate some RF/T... I have tried multiple recipes even just down to the most basic one below, where I dont even attempt to use ash with the recipe.  What could be causing this issue.
Machine Build: https://pastebin.com/UGgjvGqw
Recipe Build: https://pastebin.com/5pNTvtwy

**Comment by Boolyman** [comment]
Also to clarify, the multiblock forms fine, and the world was loaded multiple times with the multiblock.  It wasn't until I put in the recipe that the crash began happening.

**Comment by talonos2** [comment]
Can confirm: 

When I have this recipe enabled:

https://pastebin.com/raw/RMD5ivXB

Then loading a world containing this machine:

https://pastebin.com/raw/dy1C918E

Will throw this error and crash the server:

https://pastebin.com/raw/RMD5ivXB

Crossposted to Modular Machinery's main page.

**Comment by DaedalusGame** [comment]
As of MD 1.0 this crash will no longer happen with MM 1.9+
