### ISSUE TITLE
Thaumcraft Integration

### ISSUE THREAD

**Issue by Thermovale** [DaedalusGame/Modular-Diversity#18]
* Essentia input and output hatches
* vis usage?
* flux production?

**Comment by DaedalusGame** [comment]
For 1.4

```
{ 
    "type": "vis", 
    "io-type": "input", 
    "visMin": 40, 
    "visMax": 80,
    "fluxMin": 1,
    "fluxMax": 25.6,
    "flux": 5,
    "vis": -30
}
```

- Must have between 40 and 80 vis
- Must have between 1 and 25.6 flux
- Produces 5 flux
- Depletes 30 vis
- All parameters are optional
- "flux" and "vis" work for output too

**Comment by DaedalusGame** [comment]
https://github.com/Frinn38/Modular-Magic/wiki/Essentia
