### ISSUE TITLE
Better With Mods Integration

### ISSUE THREAD

**Issue by Dilnu** [DaedalusGame/Modular-Diversity#2]
Hi, If you have time and it's feasible I'd be interested in the ability to power Modular Machines with the Better With Mods Rotational power system. If that isn't feasible I understand.

**Comment by DaedalusGame** [comment]
I would like to make this work, but currently it's a bit hard to do. It's possible to convert mech power to energy internally but that's not ideal as mech power is a power level. For now, I believe you might be able to use selective nbt matching on your structure (match the power level stored in gearboxes) to achieve something similar, but it's certainly not ideal

**Comment by mvdhoning** [comment]
can you provide an example on how to match power level stored in gearboxes in my structure?

**Comment by mvdhoning** [comment]
or make an input block the checks what block is attached to it as
betterwithmods:wooden_axle@5 is an animated rotating axle (aka powered)
and
betterwithmods:wooden_axle@4 is the one you as player would place (aka non powered none animated)
what makes it behave a bit like lever being on or off
