### ISSUE TITLE
[Feature Request] Biome Detector also detects dimension and y-coordinate.

### ISSUE THREAD

**Issue by YurgenJurgensen** [DaedalusGame/Modular-Diversity#27]
This could be another block, but it makes sense for the Biome detector to detect altitude and dimension as well, and I couldn't find any indication that this is possible.  Example use cases include a "bedrock miner" which only functions at bedrock level, "wind generators" which only function at altitude, or restricting machines from functioning in pocket dimensions that have otherwise normal biomes.

**Comment by FeedCat02** [comment]
yeah a dimension detector would be really nice

**Comment by DaedalusGame** [comment]
Dimension input is now a thing

Y-coordinate shall be part of #37
