### ISSUE TITLE
Mana using machine will eat recipe components if it doesnt have enough mana

### ISSUE THREAD

**Issue by Saereth** [DaedalusGame/Modular-Diversity#30]
originally reported on our tracker here:
https://github.com/Vyraal1/FTB-Interactions/issues/353

essentially this machine takes mana + liquid ethanol, redstone and a power catalyst from bloodmagic (5% consume chance) but if they are running it and not enough mana is supplied it seems to just eat it all.

here is the recipe file:
https://hastebin.com/cofujabuxo.json

**Comment by Saereth** [comment]
confirmed this with other players and myself now, including it producing water

**Comment by DaedalusGame** [comment]
probably fixed at some point???????
