### ISSUE TITLE
Time Sensor related recipe not working

### ISSUE THREAD

**Issue by misterplus** [DaedalusGame/Modular-Diversity#40]
Machine: https://pastebin.com/8B130sCn
For some reason this recipe won't get registered :
https://pastebin.com/8SzpGCWb

But when I remove the time requirement, it works fine:
https://pastebin.com/0EQM5uEg

I think this is an issue in your mod, not my script.

**Comment by desagas** [comment]
Did you find a fix for this by any chance?

**Comment by DaedalusGame** [comment]
yes, remove the time hatch from your machine
