### ISSUE TITLE
Time Detector Modulo NOT (optional).

### ISSUE THREAD

**Issue by desagas** [DaedalusGame/Modular-Diversity#46]
Using the latest version of FTB Interactions, and this mod in 1.5, not the latest of 8, if the modulo tag is not set in a recipe, it will NOT work. IT will set the "after every ___ ticks" to 9223372036854775807. However, your current documentation states that it is option, but, sadly, it is not optional within your current code.

I have tested and confirmed this with the mod alone by itself on a 1.12.2, under the same version of forge 2838, and 1.10.0 modular machinery. Was or is there a fix in the latest version?

**Comment by DaedalusGame** [comment]
it is optional. the only bug is that it shows the "after every x ticks" if x is long.max
if you omit it, the timespan in which the recipe works will occur only once in the lifetime of planet earth. Example: you can make a recipe that works only after the world has been running for an ingame month or similar.

**Comment by desagas** [comment]
You keep closing these, but it does not work. It’s too bad, since it is a good mod otherwise. Maybe one day you’ll see that your code does not work for the daylight sensor. Nothing works when it is part of a recipe, period. Time does not matter, modulo does not matter. You can have it change dirt to stone if you wanted to, simple simple simple, and it does not work.

I’m not telling that it is not working to be rude, I’m tell you so that you know. I guess at this point, can you suggest or post a code for any recipe what so ever that actually works when you test your code, with the daylight sensor (time sensor). This would show the community 2 things: that you tested it, and that it works. Because, right now, it does not.

Denver Leman

On Sep 5, 2019, at 12:34 AM, BordListian <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #46<https://github.com/DaedalusGame/Modular-Diversity/issues/46>.

**Comment by DaedalusGame** [comment]
@desagas I hope pinging you in a closed issue will bring this to your attention since apparently you didn't read my reply in the other issue.

I have tested time requirements. And they do work.
![java_4ww3xIamhD](https://user-images.githubusercontent.com/9559216/64363961-2fb6ab00-d012-11e9-98d3-8fcae0fba4ea.png)
![java_EcysQq7hL5](https://user-images.githubusercontent.com/9559216/64363968-32b19b80-d012-11e9-8cb8-87637b12d626.png)

The time requirement in this case looks like this:
```
        {
            "type": "daylight",
            "io-type": "input",
            "start": 12000,
            "stop": 24000,
            "modulo": 24000,
            "local": true
        }
```

The machine does not have a time detector. If your machine has a time detector, it will not work. You have to remove the time detector from your machine.

**Comment by desagas** [comment]
Ah, so I was right, I just missed the part where you said to remove it. I was confused because I thought it was associated with the actual daylightsensor block. Sorry about that. Thank you for clarifying. :).

Denver Leman

On Sep 5, 2019, at 11:22 AM, BordListian <notifications@github.com<mailto:notifications@github.com>> wrote:


@desagas<https://github.com/desagas> I hope pinging you in a closed issue will bring this to your attention since apparently you didn't read my reply in the other issue.

I have tested time requirements. And they do work.
[java_4ww3xIamhD]<https://user-images.githubusercontent.com/9559216/64363961-2fb6ab00-d012-11e9-98d3-8fcae0fba4ea.png>
[java_EcysQq7hL5]<https://user-images.githubusercontent.com/9559216/64363968-32b19b80-d012-11e9-8cb8-87637b12d626.png>

The time requirement in this case looks like this:

        {
            "type": "daylight",
            "io-type": "input",
            "start": 12000,
            "stop": 24000,
            "modulo": 24000,
            "local": true
        }


The machine does not have a time detector. If your machine has a time detector, it will not work. You have to remove the time detector from your machine.
