### ISSUE TITLE
Mechanical Output doesnt turn axles

### ISSUE THREAD

**Issue by Boolyman** [DaedalusGame/Modular-Diversity#49]
I'm trying to make a very simple modular machine that turns lava into mechanical power output.  However, the mechanical out put isnt turning the axles, even though the recipe is processing in the machine.  Any idea why?  
Recipe file:  https://pastebin.com/5brCfJzK

![2019-09-14 14_50_44-Greenshot](https://user-images.githubusercontent.com/24765883/64913115-8c475380-d6ff-11e9-9002-52cd519ca5d4.png)

Yes, there are gears on each input and output of the gearbox and actuator.

**Comment by DaedalusGame** [comment]
yeah, axles don't pull mechanical power and i forgot some code on mech output hatches to make them push. if you put a gearbox next to the output hatch you can fix that temporarily

**Comment by Boolyman** [comment]
Ok, I put a gearbox on the output and it works... however, now it seems to run even after exhausting the lava in the fluid input.

**Comment by DaedalusGame** [comment]
If you hold shift you access the opposite side on a gearbox

**Comment by Boolyman** [comment]
Is there a new limit to the number of gearboxes/axles that can spin off one output?

**Comment by DaedalusGame** [comment]
no, if you want it to only output to one side you'll have to put blocks as part of the machine that prevent you from accessing the 5 other sides

**Comment by Boolyman** [comment]
Any idea why it continues to run forever even when there is no lava input left?  It doesnt do it when initially assembled... but once you put a bit of lava in, it will run forever.

**Comment by DaedalusGame** [comment]
i need to look into it

**Comment by Boolyman** [comment]
Is there any progress on this?  Since the last update the axle doesnt even turn anymore so I had to roll it back a version

**Comment by DaedalusGame** [comment]
[you tell me](https://www.curseforge.com/minecraft/mc-mods/modular-diversity/files/2804291)

**Comment by DaedalusGame** [comment]
fixed for good now
